export const NAV_TYPES = {
  // 全部
  all: 'all',
  // 选择题
  choice: 'choice',
  // JavaScript
  javaScript: 'javaScript',
  // CSS
  css: 'css',
  // HTML
  html: 'html',
  // 编程题
  programme: 'programme',
  // React.js
  reactJs: 'reactJs',
  // 微信小程序
  miniprogram: 'miniprogram',
  // Vue.js
  vueJs: 'vueJs',
  // 趣味题,
  interest: 'interest',
  // LeetCode
  leetCode: 'leetCode',
  // 算法
  algorithm: 'algorithm',
  // 计算机网络
  network: 'network',
  // Node.js
  nodeJs: 'nodeJs',
  // TypeScript
  typeScript: 'typeScript',
  // 性能优化
  performance: 'performance',
  // 前端安全
  security: 'security',
  // ES6
  es6: 'es6',
  // 设计模式
  designMode: 'designMode',
  // 工程化
  engineering: 'engineering',
  // 工具
  tools: 'tools',
  // 计算机基础
  basis: 'basis'
}